# Goal definition
geometry_msgs/PoseStamped pose_stamped
bool linear_motion
# TODO: refactor speed to vel_scale
float32 speed   # 0.0 - 1.0 scale of max gain (Linear) or max speed (Point-To-Point)
# Alternative Control Paradigm (Time Based)
float32 time    # in seconds
---
# Result definition
bool success
---
# Feedback definition
int8 status
