# Goal definition
geometry_msgs/PoseStamped pose_stamped
bool linear_motion
# Alternative Control Paradigm (Time Based)
float32 time    # in seconds
---
# Result definition
bool success
---
# Feedback definition
int8 status
